"""updated user table

Revision ID: 50ff04caac68
Revises: 6ec0da7ecccf
Create Date: 2026-04-16 19:44:43.778952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50ff04caac68'
down_revision: Union[str, None] = '6ec0da7ecccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('PasswordHash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('AuthProvider', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('EmailVerified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('PhoneVerified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('SchoolVerified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('IdentityVerified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('ProfilePhotoUrl', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('ProfilePhotoStatus', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('VerificationStatus', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('AccountStatus', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('IsDeleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('UpdatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('LastLoginAt', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'UserID',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('nextval(\'"users_UserID_seq"\'::regclass)'))
    op.alter_column('users', 'BirthDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'CreatedAt',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('users', 'Password')
    op.drop_column('users', 'isDeleted')
    op.drop_column('users', 'LastLogin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('LastLogin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('isDeleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('Password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'CreatedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'BirthDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'UserID',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('nextval(\'"users_UserID_seq"\'::regclass)'))
    op.drop_column('users', 'LastLoginAt')
    op.drop_column('users', 'UpdatedAt')
    op.drop_column('users', 'IsDeleted')
    op.drop_column('users', 'AccountStatus')
    op.drop_column('users', 'VerificationStatus')
    op.drop_column('users', 'ProfilePhotoStatus')
    op.drop_column('users', 'ProfilePhotoUrl')
    op.drop_column('users', 'IdentityVerified')
    op.drop_column('users', 'SchoolVerified')
    op.drop_column('users', 'PhoneVerified')
    op.drop_column('users', 'EmailVerified')
    op.drop_column('users', 'AuthProvider')
    op.drop_column('users', 'PasswordHash')
    # ### end Alembic commands ###
