"""create users table

Revision ID: 6ec0da7ecccf
Revises: 
Create Date: 2026-04-14 20:20:30.516748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec0da7ecccf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Password', sa.String(), nullable=True),
    sa.Column('UserName', sa.String(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=False),
    sa.Column('LastName', sa.String(), nullable=False),
    sa.Column('BirthDate', sa.Date(), nullable=True),
    sa.Column('Phone', sa.String(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('LastLogin', sa.DateTime(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('AccountSetup', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_index(op.f('ix_users_Email'), 'users', ['Email'], unique=True)
    op.create_index(op.f('ix_users_UserID'), 'users', ['UserID'], unique=False)
    op.create_index(op.f('ix_users_UserName'), 'users', ['UserName'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_UserName'), table_name='users')
    op.drop_index(op.f('ix_users_UserID'), table_name='users')
    op.drop_index(op.f('ix_users_Email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
