"""Fixed/Updated User table for -> Auth API calls | auth_codes | few API calls for User verified

Revision ID: c64f98082e73
Revises: 50ff04caac68
Create Date: 2026-04-20 00:32:11.303746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64f98082e73'
down_revision: Union[str, None] = '50ff04caac68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['Phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
