"""rechecking crashes

Revision ID: cfc70ddf451a
Revises: c64f98082e73
Create Date: 2026-04-20 14:28:07.777848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc70ddf451a'
down_revision: Union[str, None] = 'c64f98082e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_codes',
    sa.Column('AuthCodeID', sa.BigInteger(), nullable=False),
    sa.Column('UserID', sa.BigInteger(), nullable=False),
    sa.Column('Code', sa.String(length=10), nullable=False),
    sa.Column('CodeType', sa.String(length=30), nullable=False),
    sa.Column('Target', sa.String(length=255), nullable=True),
    sa.Column('IsUsed', sa.Boolean(), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UsedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('AuthCodeID')
    )
    op.create_index(op.f('ix_auth_codes_AuthCodeID'), 'auth_codes', ['AuthCodeID'], unique=False)
    op.create_index(op.f('ix_auth_codes_Code'), 'auth_codes', ['Code'], unique=False)
    op.create_index(op.f('ix_auth_codes_CodeType'), 'auth_codes', ['CodeType'], unique=False)
    op.create_index(op.f('ix_auth_codes_UserID'), 'auth_codes', ['UserID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_codes_UserID'), table_name='auth_codes')
    op.drop_index(op.f('ix_auth_codes_CodeType'), table_name='auth_codes')
    op.drop_index(op.f('ix_auth_codes_Code'), table_name='auth_codes')
    op.drop_index(op.f('ix_auth_codes_AuthCodeID'), table_name='auth_codes')
    op.drop_table('auth_codes')
    # ### end Alembic commands ###
