"""create email and phone verification tables

Revision ID: f6f0bed28f46
Revises: cfc70ddf451a
Create Date: 2026-04-20 14:58:08.541838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f0bed28f46'
down_revision: Union[str, None] = 'cfc70ddf451a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_codes',
    sa.Column('ID', sa.BigInteger(), nullable=False),
    sa.Column('UserID', sa.BigInteger(), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Code', sa.String(length=10), nullable=False),
    sa.Column('Purpose', sa.String(length=30), nullable=False),
    sa.Column('IsUsed', sa.Boolean(), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_email_verification_codes_Email'), 'email_verification_codes', ['Email'], unique=False)
    op.create_index(op.f('ix_email_verification_codes_ID'), 'email_verification_codes', ['ID'], unique=False)
    op.create_index(op.f('ix_email_verification_codes_UserID'), 'email_verification_codes', ['UserID'], unique=False)
    op.create_table('phone_verification_codes',
    sa.Column('ID', sa.BigInteger(), nullable=False),
    sa.Column('UserID', sa.BigInteger(), nullable=False),
    sa.Column('Phone', sa.String(length=30), nullable=False),
    sa.Column('Code', sa.String(length=10), nullable=False),
    sa.Column('Purpose', sa.String(length=30), nullable=False),
    sa.Column('IsUsed', sa.Boolean(), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_phone_verification_codes_ID'), 'phone_verification_codes', ['ID'], unique=False)
    op.create_index(op.f('ix_phone_verification_codes_Phone'), 'phone_verification_codes', ['Phone'], unique=False)
    op.create_index(op.f('ix_phone_verification_codes_UserID'), 'phone_verification_codes', ['UserID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_verification_codes_UserID'), table_name='phone_verification_codes')
    op.drop_index(op.f('ix_phone_verification_codes_Phone'), table_name='phone_verification_codes')
    op.drop_index(op.f('ix_phone_verification_codes_ID'), table_name='phone_verification_codes')
    op.drop_table('phone_verification_codes')
    op.drop_index(op.f('ix_email_verification_codes_UserID'), table_name='email_verification_codes')
    op.drop_index(op.f('ix_email_verification_codes_ID'), table_name='email_verification_codes')
    op.drop_index(op.f('ix_email_verification_codes_Email'), table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    # ### end Alembic commands ###
